In [1]:
import faiss
import numpy as np

In [2]:
index = faiss.read_index(r"C:\Users\amitp\cs-project\gods_eye\data\faiss\faces_index.index")

In [3]:
import deepface_encapsulator

In [5]:
import numpy as np
import cv2

with open(r"C:\Users\amitp\cs-project\gods_eye\data\faces\web\20240320_114205.jpg", 'rb') as f:
    content = f.read()

    image_data = np.frombuffer(content, dtype=np.uint8)
    image = cv2.imdecode(image_data, cv2.IMREAD_COLOR)
image

array([[[117,  96,  95],
        [125, 107, 106],
        [ 24,  10,  11],
        ...,
        [ 21,  23,  24],
        [ 24,  23,  25],
        [ 23,  22,  24]],

       [[128, 107, 106],
        [132, 114, 113],
        [ 32,  20,  20],
        ...,
        [ 24,  26,  27],
        [ 26,  25,  27],
        [ 26,  25,  27]],

       [[127, 106, 108],
        [129, 113, 114],
        [ 42,  29,  31],
        ...,
        [ 32,  34,  35],
        [ 31,  30,  32],
        [ 31,  30,  32]],

       ...,

       [[ 80,  81,  79],
        [ 81,  82,  80],
        [ 81,  82,  80],
        ...,
        [ 37,  57,  82],
        [ 38,  59,  81],
        [ 38,  59,  81]],

       [[ 81,  82,  78],
        [ 81,  82,  78],
        [ 82,  83,  81],
        ...,
        [ 38,  58,  83],
        [ 40,  61,  83],
        [ 41,  62,  84]],

       [[ 84,  83,  79],
        [ 84,  83,  79],
        [ 84,  82,  81],
        ...,
        [ 38,  58,  83],
        [ 42,  63,  85],
        [ 44,  65,  87]]

In [7]:
model = deepface_encapsulator.FeatureExtractor()


In [157]:
import uuid
embedding = model.represent(image)[0]['embedding']
np.expand_dims(embedding, axis=0)
index = faiss.IndexFlatL2(128)
index = faiss.IndexIDMap(index)
index.add_with_ids(np.expand_dims(embedding, axis=0), np.array((uuid.uuid4().int & ((1 << 64) - 1))).astype('int64'))

In [153]:
np.array((uuid.uuid4().int & ((1 << 64) - 1))).astype('uint64')

array(13087109171767709362, dtype=uint64)

In [162]:
index.add_with_ids(np.expand_dims(embedding, axis=0), np.array((uuid.uuid4().int & ((1 << 64) - 1))).astype('int64'))

In [177]:
index.search(np.expand_dims(embedding, axis=0), 5)

(array([[0.0000000e+00, 0.0000000e+00, 3.4028235e+38, 3.4028235e+38,
         3.4028235e+38]], dtype=float32),
 array([[-6174049859093649238, -8173371359464114154,                   -1,
                           -1,                   -1]], dtype=int64))

In [173]:
with open(r"C:\Users\amitp\cs-project\gods_eye\data\faces\web\20240320_114208.jpg", 'rb') as f:
    content = f.read()

    image_data = np.frombuffer(content, dtype=np.uint8)
    image = cv2.imdecode(image_data, cv2.IMREAD_COLOR)

In [178]:
embedding2 = model.represent(image)[0]['embedding']

In [189]:
index.search(np.expand_dims(embedding2, axis=0),5)


(array([[8.0179462e+00, 8.0179462e+00, 3.4028235e+38, 3.4028235e+38,
         3.4028235e+38]], dtype=float32),
 array([[-6174049859093649238, -8173371359464114154,                   -1,
                           -1,                   -1]], dtype=int64))

In [181]:
model.find_threshold()

0.8

In [186]:
def genrate_ids(n: int):
        return np.array([(uuid.uuid4().int & ((1 << 64) - 1)) for _ in range(n)]).astype('int64')
genrate_ids(100)

array([-5995069667505077051, -8326794940784798323, -8012097212657313733,
       -6166518652642895901, -8147818962007891358, -6363286773728839858,
       -7740712415945365646, -6017731234426008056, -9152510885823312646,
       -6574100092285589487, -5335632659403958453, -5495702820190802307,
       -7668869741950020227, -7881065372651498754, -4991807790496372309,
       -7729503273579789583, -7571630643260882911, -8406349861121488316,
       -8542169672598004909, -8227061736066251176, -8486544024235300235,
       -8904039623707806669, -7904986489500218833, -8243143108059872603,
       -7804675565549545980, -5844979344492858842, -4726303534987408489,
       -6121726283183884927, -7632805082883581382, -5010916618491104889,
       -7391027444615665778, -6897098454012200524, -4979596273798233883,
       -4795243642765931475, -7429558061840191230, -7801612123474395593,
       -6434111167547386005, -4643846120745320205, -5921192278303942556,
       -7950772183976695349, -8613397940344563647, 